name: SSAT
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.5
  - pip=20.3
  - cudatoolkit=11.0
  - pytorch
  - torchvision
  - numpy
  - pip:
    - opencv-python==4.1.2.30
    - imageio==2.9.0
    - dlib==19.24.2
    